using _1;
Console.Write("Введите название журнала: ");
string name = Console.ReadLine();
Console.Write("Введите тираж: ");
int circulation = int.Parse(Console.ReadLine());
Console.Write("Введите цену: ");
int price = int.Parse(Console.ReadLine());
Magazine magazine = new Magazine(circulation,price,name);
Console.WriteLine(magazine);
Console.Write($"Circulation cost: {magazine.CirculationCost()}");
Console.WriteLine();
Console.Write("Введите название газеты: ");
string name1 = Console.ReadLine();
Console.Write("Введите тираж: ");
int circulation1 = int.Parse(Console.ReadLine());
Console.Write("Введите количество страниц: ");
int count = int.Parse(Console.ReadLine());
Console.Write("Введите стоимость одной страницы: ");
double cost = double.Parse(Console.ReadLine());
Newspaper newspaper = new Newspaper(count,cost,circulation1,name1);
Console.WriteLine(newspaper);
Console.Write($"Circulation cost: {newspaper.NewapaperCirculationCost()}");